### ISSUE TITLE
Missing data for wb97x-d3 set

### ISSUE THREAD

**Issue by puckvg** [hesther/reactiondatabase#1]
Hi there, 

In the data/ folder the .csv file is missing for the wb97x-d3 set. Could you upload it please? I want to match it up to the splits.

Thanks!

**Comment by hesther** [comment]
Hi, sorry for the late response! The data folder only holds datasets that were created or adapted for the current study. The wb97x-d3 set was taken as is from [DOI:10.1038/s41597-020-0460-4](https://doi.org/10.1038/s41597-020-0460-4), the direkt download can be found [here](https://zenodo.org/record/3715478#.Y6NqPi-B2gQ), file wb97xd3.csv

Let me know if you have trouble accessing the file, then I can also upload it here.
